
package introsde.assignment.soap.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "People", targetNamespace = "http://webservice.soap.assignment.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface People {


    /**
     * 
     * @param personId
     * @return
     *     returns introsde.assignment.soap.webservice.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "http://webservice.soap.assignment.introsde/")
    @RequestWrapper(localName = "readPerson", targetNamespace = "http://webservice.soap.assignment.introsde/", className = "introsde.assignment.soap.webservice.ReadPerson")
    @ResponseWrapper(localName = "readPersonResponse", targetNamespace = "http://webservice.soap.assignment.introsde/", className = "introsde.assignment.soap.webservice.ReadPersonResponse")
    @Action(input = "http://webservice.soap.assignment.introsde/People/readPersonRequest", output = "http://webservice.soap.assignment.introsde/People/readPersonResponse")
    public Person readPerson(
        @WebParam(name = "personId", targetNamespace = "")
        int personId);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.assignment.soap.webservice.Person>
     */
    @WebMethod
    @WebResult(name = "people", targetNamespace = "")
    @RequestWrapper(localName = "getPeopleList", targetNamespace = "http://webservice.soap.assignment.introsde/", className = "introsde.assignment.soap.webservice.GetPeopleList")
    @ResponseWrapper(localName = "getPeopleListResponse", targetNamespace = "http://webservice.soap.assignment.introsde/", className = "introsde.assignment.soap.webservice.GetPeopleListResponse")
    @Action(input = "http://webservice.soap.assignment.introsde/People/getPeopleListRequest", output = "http://webservice.soap.assignment.introsde/People/getPeopleListResponse")
    public List<Person> getPeopleList();

    /**
     * 
     * @param person
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "personId", targetNamespace = "")
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://webservice.soap.assignment.introsde/", className = "introsde.assignment.soap.webservice.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://webservice.soap.assignment.introsde/", className = "introsde.assignment.soap.webservice.CreatePersonResponse")
    @Action(input = "http://webservice.soap.assignment.introsde/People/createPersonRequest", output = "http://webservice.soap.assignment.introsde/People/createPersonResponse")
    public int createPerson(
        @WebParam(name = "person", targetNamespace = "http://webservice.soap.assignment.introsde/")
        Person person);

    /**
     * 
     * @param person
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "personId", targetNamespace = "")
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://webservice.soap.assignment.introsde/", className = "introsde.assignment.soap.webservice.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://webservice.soap.assignment.introsde/", className = "introsde.assignment.soap.webservice.UpdatePersonResponse")
    @Action(input = "http://webservice.soap.assignment.introsde/People/updatePersonRequest", output = "http://webservice.soap.assignment.introsde/People/updatePersonResponse")
    public int updatePerson(
        @WebParam(name = "person", targetNamespace = "http://webservice.soap.assignment.introsde/")
        Person person);

    /**
     * 
     * @param personId
     */
    @WebMethod
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://webservice.soap.assignment.introsde/", className = "introsde.assignment.soap.webservice.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://webservice.soap.assignment.introsde/", className = "introsde.assignment.soap.webservice.DeletePersonResponse")
    @Action(input = "http://webservice.soap.assignment.introsde/People/deletePersonRequest", output = "http://webservice.soap.assignment.introsde/People/deletePersonResponse")
    public void deletePerson(
        @WebParam(name = "personId", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Integer> personId);

}
